update start files
Signed-off-by: Stefan Bischof <stbischof@bipolis.org>

diff --git a/application/probe/start b/application/probe/start
--- a/application/probe/start
+++ b/application/probe/start
@@ -1,14 +1,14 @@
 #!/bin/bash
 
 # Path to Java-Binary
-JAVA_EXEC="./java/bin/java"
+JAVA_EXEC="java"
 
 # Logback-Konfiguration
 LOGBACK_CONFIG="./logback.xml"
 
-# Check Java
-if [[ ! -x "$JAVA_EXEC" ]]; then
-  echo "Java-Binary $JAVA_EXEC not found."
+# Check if java -version returns output successfully
+if ! "$JAVA_EXEC" -version >/dev/null 2>&1; then
+  echo "Java is installed but not working properly (java -version failed)."
   exit 1
 fi
 
@@ -20,6 +20,5 @@ fi
 
 # start Server
 echo "start Server"
-"$JAVA_EXEC" -Dlogback.configurationFile=file:"$LOGBACK_CONFIG" -jar database-probe.jar
-
+"$JAVA_EXEC" -Dlogback.configurationFile=file:"$LOGBACK_CONFIG" -jar daanse.probe.jar
 
